### ISSUE TITLE
transient file access error

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#257]
received this in sentry:

```python
ERROR:cdci_data_analysis.flask_app.dispatcher_query:failed to get query products
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 507, in get_query_products
    prod_list = self.build_product_list(instrument,res, scratch_dir,api=api)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_image_query.py", line 185, in build_product_list
    catalog=OsaIsgriCatalog.build_from_ddosa_srclres(
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_catalog.py", line 95, in build_from_ddosa_srclres
    catalog=FitsFile(srclres).open()[1]
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/io_helper.py", line 81, in open
    return pf.open(self.file_path.path)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 173, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 408, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1090, in _readfrom
    raise OSError('No SIMPLE card found, this file does not '
OSError: No SIMPLE card found, this file does not appear to be a valid FITS file
```

The file is there and is good. Must be some filesystem sync error. May need to retry here few times with a short delay, and write the error more clearly.

**Comment by burnout87** [comment]
It's really hard to understand. I guess that, as you also have suspected, this is some sort of a filesistem synchronization error, also difficult to reproduce. So, let's keep it in mind and reopen in case it happens again.

**Comment by volodymyrss** [comment]
Yes, but  a possibility for reliability would be to retry here few times with a short delay, and write the error more clearly.

**Comment by burnout87** [comment]
I don't have access to sentry, so I cannot actually see if the same error happened again after my attempts to perform some stress tests (well, also clutter the email server :( ).

Anyway, did you receive something?

**Comment by volodymyrss** [comment]
I saw nothing. Did you see any errors in the logs?

**Comment by burnout87** [comment]
No, just connection timeout(s).

**Comment by volodymyrss** [comment]
These queries did not cause much post-processing. They are not definitive. So I suggest as before:
* retry here a few times in a loop, with `time.sleep(1)`  in case of failure
* write the error more clearly: indicate which file is problematic

**Comment by burnout87** [comment]
> These queries did not cause much post-processing. 
>
Could you suggest one that would cause it?
> 
>     * write the error more clearly: indicate which file is problematic

You mean as output log?

**Comment by volodymyrss** [comment]
> > These queries did not cause much post-processing.
> 
> Could you suggest one that would cause it?

Maybe, but I'd rather not stress it now. And proceed with workaround (and other issues).

> 
> > ```
> > * write the error more clearly: indicate which file is problematic
> > ```
> 
> You mean as output log?

Yes, and also sentry.
