### ISSUE TITLE
creating of `temp_sid_XXXXX` is not thread-safe

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#259]
I get this message in RequestNotUnderstood.

this is log

```python
ERROR:[ InstrumentQueryBackEnd : instrument-not-set ]:traceback: Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/io_helper.py", line 168, in mkdir
    self._file_path.mkdir()
  File "/pyenv/versions/3.8.5/lib/python3.8/pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: 'temp_sid_Y0CQ65ZT4WN6ISIG'

During handling of the above exception, another exception occurred:
APIerror RequestNotUnderstood() constructor: [ InstrumentQueryBackEnd : isgri ] constructor failed: ('!Error error ', FileExistsError(17, 'File exists'), 'in creating dir', 'temp_sid_Y0CQ65Z
T4WN6ISIG')

Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/dispatcher_query.py", line 234, in __init__
    self.set_temp_dir(self.par_dic['session_id'], verbose=verbose)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/dispatcher_query.py", line 530, in set_temp_dir
    td.mkdir()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/io_helper.py", line 170, in mkdir
    raise RuntimeError('!Error error ',e,'in creating dir', self.path)
RuntimeError: ('!Error error ', FileExistsError(17, 'File exists'), 'in creating dir', 'temp_sid_Y0CQ65ZT4WN6ISIG')
```

it fails when there are multiple dispatcher processes, preventing scaling. I think it also fails with one process but many threads, but less often.

I reduce number of processes for now, and make a hotfix

**Comment by volodymyrss** [comment]
I did not fully trace why the directory creation is conflicting. I am mildly concerned simple change will introduce issues. Right now, I will just reduce parallelism. Unfortunately, at high load (as I am doing now), with many catalogs, it seems to happens.

But I am not even entirely sure it's due to parallelism. Could be it's when `set_temp_dir` is called for the same session and no job id (apparently?). 

Maybe even bigger issue is that user gets error and we do not.

**Comment by volodymyrss** [comment]
This might be helpful https://github.com/oda-hub/dispatcher-app/tree/hotfix-259

**Comment by burnout87** [comment]
Indeed it is! Really interesting also!
