### ISSUE TITLE
download products problem 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#366]
could it be related to new flask?

I see this in dispatcher log:

ERROR:cdci_data_analysis.flask_app.app:Exception on /download_products [GET]
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a TypeError.

**Comment by dsavchenko** [comment]
Exception is raised here https://github.com/oda-hub/dispatcher-app/blob/a73906e69dd36f1d30e1cee08f7250047fdaae7c/cdci_data_analysis/flask_app/dispatcher_query.py#L809
The name of the second parameter was `filename`, compatible with old flask/werkzeug but incompatible with the new ones
Now it should be `path`, but this produces exception with old ones

**Comment by dsavchenko** [comment]
If https://github.com/oda-hub/dispatcher-container is used to build the container, it could cause an error: requirements.txt there contains restriction on werkzeug version
Generally, the duplication of dependencies there is unnecessary

**Comment by volodymyrss** [comment]
yeah, I just updated, its deploying

**Comment by dsavchenko** [comment]
> which one do we need?

The latest is 2.0.3 for both, and it works. Should we restrict it?

**Comment by volodymyrss** [comment]
I pushed master accidentially

**Comment by volodymyrss** [comment]
please check now to confirm

**Comment by dsavchenko** [comment]
Works now
