### ISSUE TITLE
	failed: isgri_lc 	TypeError('Cannot compare structured or void to non-void arrays.')

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#492]
it's a bug and it obstucts @ferrigno . Not sure if this is not plugin. I try to address quickly but I am a bit blocked by the meeting.

if @burnout87 can help quickly it's much appreciated. Else I do a bit later.

https://sentry.io/organizations/cdci/issues/3805109826/?query=is%3Aunresolved&referrer=issue-stream

![image](https://user-images.githubusercontent.com/3909535/207638005-9f4ec84e-925a-4c19-bcae-cfaf3dcf1b09.png)

**Comment by volodymyrss** [comment]
this is not properly captured to sentry

```python
ERROR:cdci_data_analysis.flask_app.dispatcher_query:failed to get query products
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 523, in get_query_products
    prod_list = self.build_product_list(instrument,res, scratch_dir,api=api)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_lightcurve_query.py", line 457, in build_product_list
    prod_list = OsaLightCurve.build_isgri_lc_from_ddosa_res(res,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_lightcurve_query.py", line 150, in build_isgri_lc_from_ddosa_res
    OsaLightCurve.ensure_timedel(du)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_lightcurve_query.py", line 94, in ensure_timedel
    if 'TIMEDEL' in du.data:
TypeError: Cannot compare structured or void to non-void arrays.

```
